name: Publish
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: package
    displayName: Package
    type: boolean
    values:
      - SocketIOClient
      - SocketIOClient.Windows7
      - SocketIOClient.Newtonsoft.Json

jobs:
  - job:
    displayName: Publish
    steps:
      - pwsh: |
          dotnet pack -c Release --output $(Build.ArtifactStagingDirectory)
          $packageName = Get-ChildItem $(Build.ArtifactStagingDirectory)/SocketIOClient.*.nupkg | Select-Object -First 1 -ExpandProperty Name
          Write-Host "##vso[task.setvariable variable=packageName;]$packageName"
          # dotnet nuget push $packageName --api-key AzureArtifacts --source nuget.org
        displayName: dotnet pack
        workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient
      # - task: PowerShell@2
      #   displayName: dotnet pack
      #   inputs:
      #     pwsh: true
      #     workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient
      #     script: |
      #       dotnet pack -c Release --output $(Build.ArtifactStagingDirectory)
      #       $packageName = Get-ChildItem SocketIOClient.*.nupkg | Select-Object -First 1 -ExpandProperty Name
      #       Write-Host "##vso[task.setvariable variable=packageName;]$packageName"
      #       # dotnet nuget push $packageName --api-key AzureArtifacts --source nuget.org
      - task: CmdLine@2
        displayName: Publish to nuget.org
        inputs:
          workingDirectory: $(Agent.ArtifactStagingDirectory)
          script: |
            echo $(packageName)
