name: Unit Tests and Integration Tests

trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: NET_Tests
    jobs:
      - template: templates/nodejs-tpl.yml
      - job: ut
        displayName: Run unit tests
        steps:
          - task: DotNetCoreCLI@2
            displayName: Run unit tests
            inputs:
              workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient.UnitTest
              command: test
      - job:
        displayName: Run integration tests
        dependsOn:
          - nodejs
          - ut
        steps:
          - template: templates/socket.io-tpl.yml
          - task: DotNetCoreCLI@2
            displayName: Run integration tests
            inputs:
              workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient.IntegrationTests
              command: test
  - stage: NET_Framework_Tests
    pool: windows-latest
    jobs:
      - template: templates/nodejs-tpl.yml
      - job:
        displayName: Run integration tests for .Net Framework
        dependsOn: nodejs
        steps:
          - template: templates/socket.io-tpl.yml
          - task: MSBuild@1
            inputs:
              solution: $(Agent.BuildDirectory)/s/src/SocketIOClient.IntegrationTests.Net472/SocketIOClient.IntegrationTests.Net472.csproj