name: Unit Tests and Integration Tests

trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CheckFormat
    jobs:
      - job:
        displayName: Check format
        steps:
          - script: |
              dotnet tool restore
              dotnet format --verify-no-changes
            displayName: Check format
  - stage: NET_Tests
    dependsOn: CheckFormat
    jobs:
      - job:
        displayName: Unit tests
        steps:
          - task: DotNetCoreCLI@2
            displayName: SocketIOClient.UnitTests
            inputs:
              workingDirectory: $(System.DefaultWorkingDirectory)/tests/SocketIOClient.UnitTests
              command: test
          - task: DotNetCoreCLI@2
            displayName: SocketIO.Serializer.SystemTextJson.Tests
            inputs:
              workingDirectory: $(System.DefaultWorkingDirectory)/tests/SocketIO.Serializer.SystemTextJson.Tests
              command: test
          - task: DotNetCoreCLI@2
            displayName: SocketIO.Serializer.NewtonsoftJson.Tests
            inputs:
              workingDirectory: $(System.DefaultWorkingDirectory)/tests/SocketIO.Serializer.NewtonsoftJson.Tests
              command: test
          - task: DotNetCoreCLI@2
            displayName: SocketIO.Serializer.MessagePack.Tests
            inputs:
              workingDirectory: $(System.DefaultWorkingDirectory)/tests/SocketIO.Serializer.MessagePack.Tests
              command: test
#      - job:
#        displayName: Integration tests
#        steps:
#          - template: templates/socket.io-tpl.yml
#          - task: DotNetCoreCLI@2
#            displayName: Integration tests
#            inputs:
#              workingDirectory: $(System.DefaultWorkingDirectory)/tests/SocketIOClient.IntegrationTests
#              command: test
#  - stage: NET_Framework_Tests
#    dependsOn: CheckFormat
#    pool:
#      vmImage: windows-latest
#    jobs:
#      - job:
#        displayName: Integration tests for .Net Framework
#        steps:
#          - template: templates/socket.io-tpl.yml
#          - pwsh: dotnet restore
#            displayName: dotnet restore
#            workingDirectory: $(System.DefaultWorkingDirectory)
#          - task: MSBuild@1
#            inputs:
#              solution: $(System.DefaultWorkingDirectory)/socket.io-client-csharp.sln
#              restoreNugetPackages: true
#          - task: VSTest@2
#            inputs:
#              testAssemblyVer2: SocketIOClient.IntegrationTests.Net472.dll
#              searchFolder: $(System.DefaultWorkingDirectory)/tests/SocketIOClient.IntegrationTests.Net472/bin/Debug