name: Unit Tests and Integration Tests

trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: NET_Tests
    jobs:
      - job:
        displayName: Unit tests
        steps:
          - task: DotNetCoreCLI@2
            displayName: Unit tests
            inputs:
              workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient.UnitTest
              command: test
      - job:
        displayName: Integration tests
        steps:
          - template: templates/socket.io-tpl.yml
          - task: DotNetCoreCLI@2
            displayName: Integration tests
            inputs:
              workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient.IntegrationTests
              command: test
  - stage: NET_Framework_Tests
    dependsOn: [ ]
    pool: 
      vmImage: windows-latest
    jobs:
      - job:
        displayName: Integration tests for .Net Framework
        steps:
          - template: templates/socket.io-tpl.yml
          - pwsh: dotnet restore
            displayName: dotnet restore
            workingDirectory: $(Agent.BuildDirectory)/s/src
          - task: MSBuild@1
            inputs:
              solution: $(Agent.BuildDirectory)/s/src/socket.io-client-csharp.sln
              restoreNugetPackages: true
          - task: VSTest@2
            inputs:
              testAssemblyVer2: SocketIOClient.IntegrationTests.Net472.dll
              searchFolder: $(Agent.BuildDirectory)/s/src/SocketIOClient.IntegrationTests.Net472/bin/Debug