name: Unit Tests and Integration Tests

trigger:
  - master

pool:
  vmImage: ubuntu-latest

jobs:
  - job: nodejs
    displayName: Install nodejs
    steps:
      - checkout: none
      - task: NodeTool@0
        displayName: Install nodejs
        inputs:
          versionSpec: 16.x
  - job: ut
    displayName: Run unit tests
    steps:
      - task: DotNetCoreCLI@2
        displayName: Run unit tests
        inputs:
          workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient.UnitTest
          command: test
  - job:
    displayName: Run integration tests
    dependsOn:
      - nodejs
      - ut
    steps:
      - task: CmdLine@2
        displayName: Run socket.io server
        inputs:
          workingDirectory: $(Agent.BuildDirectory)/s/src/socket.io
          script: |
            npm install
            npm run install
            npm start &
      - task: PowerShell@2
        displayName: Check ports of socket.io servers
        inputs:
          filePath: $(Agent.BuildDirectory)/s/azure-devops/check-port.ps1
      - task: DotNetCoreCLI@2
        displayName: Run integration tests
        inputs:
          workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient.IntegrationTests
          command: test
