trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
#  - stage: CheckFormat
#    jobs:
#      - job:
#        displayName: Check format
#        steps:
#          - script: |
#              dotnet tool restore
#              dotnet format --verify-no-changes
#            displayName: Check format
  - stage: NET_Tests
#    dependsOn: CheckFormat
    jobs:
      - job:
        displayName: Unit tests
        steps:
          - task: DotNetCoreCLI@2
            displayName: SocketIOClient.UnitTests
            inputs:
              workingDirectory: $(System.DefaultWorkingDirectory)/tests/SocketIOClient.UnitTests
              command: test
              publishTestResults: true
              arguments: >
                --configuration Release
                /p:CollectCoverage=true
                /p:CoverletOutputFormat=cobertura
                /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/SocketIOClient.UnitTests/

          - task: DotNetCoreCLI@2
            displayName: SocketIOClient.Serializer.Tests
            inputs:
              workingDirectory: $(System.DefaultWorkingDirectory)/tests/SocketIOClient.Serializer.Tests
              command: test
              publishTestResults: true
              arguments: >
                --configuration Release
                /p:CollectCoverage=true
                /p:CoverletOutputFormat=cobertura
                /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/SocketIOClient.Serializer.Tests/

          - task: DotNetCoreCLI@2
            displayName: SocketIOClient.Serializer.NewtonsoftJson.Tests
            inputs:
              workingDirectory: $(System.DefaultWorkingDirectory)/tests/SocketIOClient.Serializer.NewtonsoftJson.Tests
              command: test
              publishTestResults: true
              arguments: >
                --configuration Release
                /p:CollectCoverage=true
                /p:CoverletOutputFormat=cobertura
                /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/SocketIOClient.Serializer.NewtonsoftJson.Tests/

          - script: dotnet tool install -g dotnet-reportgenerator-globaltool
            displayName: Install reportgenerator

          - script: |
              reportgenerator \
                -reports:"$(Build.SourcesDirectory)/TestResults/**/coverage.cobertura.xml" \
                -targetdir:"$(Build.SourcesDirectory)/TestResults/MergedCoverage" \
                -reporttypes:Cobertura
            displayName: Merge coverage reports

          - task: PublishCodeCoverageResults@2
            displayName: Publish code coverage
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(Build.SourcesDirectory)/TestResults/MergedCoverage/Cobertura.xml'
              reportDirectory: '$(Build.SourcesDirectory)/TestResults/MergedCoverage'
      - job:
        displayName: Integration tests
        steps:
          - template: templates/socket.io-tpl.yml
          - task: DotNetCoreCLI@2
            displayName: Integration tests
            inputs:
              workingDirectory: $(System.DefaultWorkingDirectory)/tests/SocketIOClient.IntegrationTests
              command: test

#  - stage: NET_Framework_Tests
#    dependsOn: CheckFormat
#    pool:
#      vmImage: windows-latest
#    jobs:
#      - job:
#        displayName: Integration tests for .Net Framework
#        steps:
#          - template: templates/socket.io-tpl.yml
#          - pwsh: dotnet restore
#            displayName: dotnet restore
#            workingDirectory: $(System.DefaultWorkingDirectory)
#          - task: MSBuild@1
#            inputs:
#              solution: $(System.DefaultWorkingDirectory)/socket.io-client-csharp.sln
#              restoreNugetPackages: true
#          - task: VSTest@2
#            inputs:
#              testAssemblyVer2: SocketIOClient.IntegrationTests.Net472.dll
#              searchFolder: $(System.DefaultWorkingDirectory)/tests/SocketIOClient.IntegrationTests.Net472/bin/Debug